version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5001:5001"
    command: npm start
    volumes:
      - ./server:/app/server

  client:
    build: ./client
    ports:
      - "5173:5173"
    command: npm run dev
    volumes:
      - ./client:/app/client
